### ISSUE TITLE
Newer doctrine/dbal dependency

### ISSUE THREAD

**Issue by bassim** [facile-it/doctrine-mysql-come-back#2]
Hi There, 

What are the possibilities for updating the doctrine/dbal dependency in your composer.json to a more recent version?

I'm asking, cause downgrading to  ">=2.3,<2.4-dev" seems to have broken my sf2 'kpn_paginator' sorting functionality. 

Beside that, your code was a real lifesaver for me! 

Cheers!

**Comment by dbykadorov** [comment]
@peelandsee Do I understand correctly that ping method implemented only for Doctrine\DBAL\Driver\Mysqli\MysqliConnection?

For Doctrine less than 2.5 with pdo_mysql driver I used the same method as used in your doctrine-mysql-come-back module. Thus it turns out that I need to downgrade doctrine 2 or use mysqli driver?
