### ISSUE TITLE
Undefined method named fetchAllAssociative

### ISSUE THREAD

**Issue by srebb** [facile-it/doctrine-mysql-come-back#43]
Hey and thanks for the great package which does great work.

In a current project I get the following message:
Attempted to call an undefined method named "fetchAllAssociative" of class "Facile\DoctrineMySQLComeBack\Doctrine\DBAL\Statement".   

Best regards

**Comment by thomasvargiu** [comment]
Hi @srebb,
Can you please provide us which version of `doctrine/dbal` you're using?

**Comment by srebb** [comment]
Hi @thomasvargiu,
thanks for the very fast reaction.
I use doctrine.dbal 2.12.1 with facile-it/doctrine-mysql-come-back 1.9.0

"message": "Call to undefined method Facile\\DoctrineMySQLComeBack\\Doctrine\\DBAL\\Statement::fetchAllAssociative()",
"file": "/srv/www/vhosts/projectname/current/src/Command/AC.php:189",
"trace": [
	"/srv/www/vhosts/projectname/current/src/Command/AC.php:119",
	"/srv/www/vhosts/projectname/current/src/pathToCode/AASOC.php:178",
	"/srv/www/vhosts/projectname/current/vendor/symfony/console/Command/Command.php:255",
	"/srv/www/vhosts/projectname/current/vendor/symfony/console/Application.php:1027",
	"/srv/www/vhosts/projectname/current/vendor/symfony/framework-bundle/Console/Application.php:97",
	"/srv/www/vhosts/projectname/current/vendor/symfony/console/Application.php:273",
	"/srv/www/vhosts/projectname/current/vendor/symfony/framework-bundle/Console/Application.php:83",
	"/srv/www/vhosts/projectname/current/vendor/symfony/console/Application.php:149",
	"/srv/www/vhosts/projectname/current/bin/console:42"
]
			
			
AC.php:189 is written `$statement->fetchAllAssociative();`

**Comment by thomasvargiu** [comment]
Ok, I found the "problem". That method is part of a new implementation since ` doctrine/dbal: 2.11`.
Until we'll implement those methods, I suggest you to use the old compatible methods (`fetchAll()` in this case, even if it's deprecated).

We should think whether to release a new major or not in order to implement those new methods from [`Doctrine\DBAL\Driver\Result`](https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Driver/Result.php).
cc/ @Jean85

**Comment by thomasvargiu** [comment]
Since Doctrine added that implementation, it should not be a problem if we add it too.
But I was thinking that probably we should extends the `Doctrine\DBAL\Statement` directly in order to provide all available methods, since the return signature of `Connection::prepare()` is the original `Statement`.

**Comment by Tigerman55** [comment]
Psalm flags the `fetchAll()` deprecation. Any update on this issue? If it isn't being worked on yet, I may need to use psalm suppress in the meantime.

**Comment by thomasvargiu** [comment]
We released a pre-release [`1.10.0-beta1`](https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/v1.10.0-beta1).
