### ISSUE TITLE
Migration to v2

### ISSUE THREAD

**Issue by boesing** [facile-it/doctrine-mysql-come-back#66]
Hey guys,

we are using this component in our project and want to upgrade to PHP 8.1.
It seems that the v2 beta1 contains changes from #55 

The changelog says "Removed specialized MasterSlaveConnection and PrimaryReadReplicaConnection (due to drop of corresponding classes in DBAL v3)".

I am not sure where this comes from but as of this very moment, it is still part of DBAL v3.5.1 + unreleased v4.0:
https://github.com/doctrine/dbal/blob/82483595da680180c1d360ea7fbff1ea8fb08142/src/Connections/PrimaryReadReplicaConnection.php#L77
https://github.com/doctrine/dbal/blob/0f2d257b50ebd097ea40eb67e5bd1337523ded26/src/Connections/PrimaryReadReplicaConnection.php#L75

However, since I would prefer continue using this component, I wonder if the v2 beta1 is in production somewhere in combination with latest doctrine versions.
If not, is v2 already "finalized" and only bugfixes are allowed or are you open for contributions to make it compatible with latest doctrine versions?

Regards,
Max

**Comment by Jean85** [comment]
As far as I know, someone is already using the beta in prod, but I don't know how thoroughly. As for the dropped class, it has been done because the changes in how this lib wires into DBAL rendered the extension of the driver classes no longer needed, so that specialization has been dropped.

You can find detailed instructions in the `UPGRADE-2.0.md` document: https://github.com/facile-it/doctrine-mysql-come-back/blob/master/UPGRADE-2.0.md

**Comment by Jean85** [comment]
I also remembered that we have #58 (which is incomplete). Can you report back if you are able to use the beta with the `PrimaryReadReplicaConnection` missing, or if you're encountering any issue?

**Comment by Jean85** [comment]
@boesing I've released a BETA4 with a lot of changes and fixes: https://github.com/facile-it/doctrine-mysql-come-back/releases/tag/2.0.0-BETA4

Let me know  if you have any feedback!
